# ---------------------------------------------------------------------------------------------------------------------------------
# Налаштування мережі
# Ці налаштування надають детальний контроль над поведінкою мережі та обробкою пакетів у серверному додатку.
# Налаштування цих параметрів може допомогти оптимізувати продуктивність мережі та забезпечити безпечне спілкування між сервером і клієнтами.
# ---------------------------------------------------------------------------------------------------------------------------------


# ---------------------------------------------------------------------------------------------------------------------------------
# Загальні налаштування мережі
# ---------------------------------------------------------------------------------------------------------------------------------

# Час очікування завершення
# Визначає час у секундах, протягом якого сервер очікує завершення відправки/отримання пакетів під час завершення роботи.
# За замовчуванням: 5 секунд
ShutdownWaitTime = 5

# Визначте, чи увімкнено відкидання пакетів.
# За замовчуванням: False
DropPackets = False

# Поріг відкидання пакетів
# Визначає поріг для відкидання тимчасових пакетів. Вищі значення дозволяють ставити в чергу більше пакетів
# перед початком відкидання, потенційно зменшуючи втрати пакетів за рахунок більшого використання пам'яті.
# За замовчуванням: 250
DropPacketThreshold = 250


# ---------------------------------------------------------------------------------------------------------------------------------
# Налаштування ThreadPool
# ---------------------------------------------------------------------------------------------------------------------------------

# Визначає розмір основного пулу потоків у кожному пулі потоків виконання пакетів.
# Це визначає кількість потоків, які будуть попередньо запущені та доступні для негайної обробки завдань.
# Якщо встановлено 0, розмір за замовчуванням встановлюється на кількість доступних ядер процесора.
# Більше число може обробляти більше завдань одночасно, тоді як менше число економить ресурси.
# За замовчуванням: 0 (автоматично налаштовано як кількість доступних ядер процесора * 4)
ThreadPoolSize = 4

# Визначає рівень пріоритету потоків у пулі потоків виконання пакетів.
# Це значення визначає важливість цих потоків відносно інших процесів у системі.
# Значення зазвичай коливаються від 1 (найнижчий пріоритет) до 10 (найвищий пріоритет).
# За замовчуванням: 5 (середній рівень пріоритету, придатний для загального оброблення завдань)
ThreadPriority = 5


# ---------------------------------------------------------------------------------------------------------------------------------
# Налаштування Пулів Буферів
# ---------------------------------------------------------------------------------------------------------------------------------

# Початковий коефіцієнт, розмір та розмір буфера для малих, середніх та великих пулів буферів.
# Ці пули оптимізують використання пам'яті шляхом повторного використання поширених розмірів буферів.

# Розмір Сегмента Буфера
# Розмір сегментів для динамічних буферів, які використовуються для збільшення розмірів буферів за потреби.
# За замовчуванням: 64
BufferSegmentSize = 64

# Дозволити пулу буферів динамічно збільшувати свій розмір, коли він досягає максимальної ємності.
# За замовчуванням: True
BufferPool.AutoExpandCapacity = True

# Початковий фактор
# Множник для попередньої ініціалізації пулу буферів. Вищий фактор означає, що буде попередньо створено більше буферів.
# За замовчуванням: 0 (без попередньої ініціалізації)
BufferPool.InitFactor = 0

# Порожній Пул Буферів
# Розмір та розмір буфера для порожніх буферів. Використовується для мережевих пакетів порожнього розміру.
# За замовчуванням: 100 буферів по 2 байти кожен.
BufferPool.Empty.Size = 100
BufferPool.Empty.BufferSize = 2

# Мінімальний пул буферів
# Розмір та розмір буфера для буферів мінімального розміру. Використовується для мережевих пакетів мінімального розміру.
# За замовчуванням: 100 буферів по 64 байти кожен.
BufferPool.Minimum.Size = 100
BufferPool.Minimum.BufferSize = 64

# Дуже малий пул буферів
# Розмір та розмір буфера для дуже малих буферів. Використовується для дуже малих мережевих пакетів.
# За замовчуванням: 75 буферів по 128 байт кожен.
BufferPool.VerySmall.Size = 75
BufferPool.VerySmall.BufferSize = 128

# Невеликий пул буферів
# Розмір та розмір буфера для малих буферів. Використовується для малих мережевих пакетів.
# За замовчуванням: 75 буферів по 256 байт кожен.
BufferPool.Small.Size = 75
BufferPool.Small.BufferSize = 256

# Великий малий буферний пул
# Розмір та розмір буфера для більших малих буферів. Використовується для більших малих мережевих пакетів.
# За замовчуванням: 75 буферів по 512 байт кожен.
BufferPool.LargeSmall.Size = 75
BufferPool.LargeSmall.BufferSize = 512

# Невеликий Середній Пул Буферів
# Розмір та розмір буфера для невеликих середніх буферів. Використовується для менших середніх мережевих пакетів.
# За замовчуванням: 50 буферів по 1024 байти кожен.
BufferPool.SmallMedium.Size = 50
BufferPool.SmallMedium.BufferSize = 1024

# Пул буферів середнього розміру
# Розмір та розмір буфера для буферів середнього розміру. Використовується для мережевих пакетів середнього розміру.
# За замовчуванням: 50 буферів по 2048 байт кожен.
BufferPool.Medium.Size = 50
BufferPool.Medium.BufferSize = 2048

# Великий Середній Пул Буферів
# Розмір та розмір буфера для більших середніх буферів. Використовується для більших середніх мережевих пакетів.
# За замовчуванням: 50 буферів по 4096 байт кожен.
BufferPool.LargeMedium.Size = 50
BufferPool.LargeMedium.BufferSize = 4096

# Малий великий пул буферів
# Розмір та розмір буфера для малих великих буферів. Використовується для менших великих мережевих пакетів.
# За замовчуванням: 25 буферів по 8192 байт кожен.
BufferPool.SmallLarge.Size = 25
BufferPool.SmallLarge.BufferSize = 8192

# Великий пул буферів
# Розмір та розмір буфера для великих буферів. Використовується для великих мережевих пакетів.
# За замовчуванням: 25 буферів по 16384 байт.
BufferPool.Large.Size = 25
BufferPool.Large.BufferSize = 16384

# Дуже великий пул буферів
# Розмір та розмір буфера для дуже великих буферів. Використовується для дуже великих мережевих пакетів.
# За замовчуванням: 25 буферів по 24576 байт кожен.
BufferPool.VeryLarge.Size = 25
BufferPool.VeryLarge.BufferSize = 24576

# Максимальний пул буферів
# Розмір пулу буферів та розмір буфера для буферів максимального розміру. Використовується для мережевих пакетів максимального розміру.
# За замовчуванням: 10 буферів по 32768 байт.
BufferPool.Maximum.Size = 10
BufferPool.Maximum.BufferSize = 32768
