# ---------------------------------------------------------------------------
# Sistema Bancario
# ---------------------------------------------------------------------------
# Ativa/Desativa o sistema bancario.
# Permite trocar Adena por Barras de Ouro (e vice-versa) via comandos.
BankingEnabled = False

# Quantidade de Barras de Ouro que o jogador recebe ao usar o comando ".deposit".
# Tambem e a mesma quantidade que ele perdera ao usar ".withdraw".
BankingGoldbarCount = 1

# Quantidade de Adena que o jogador recebe ao usar o comando ".withdraw".
# Tambem e a mesma quantidade que ele perdera ao usar ".deposit".
BankingAdenaCount = 1000000000
