# ---------------------------------------------------------------------------
# Localizar PvP
# ---------------------------------------------------------------------------
# Exemplo de bypass para usar em NPCs:
# <a action="bypass -h FindPvP">Ir para PvP!</a>
# Ativa o bypass FindPvP, que teleporta o jogador para a zona de PvP mais movimentada.
# Padrao: False
EnableFindPvP = False
