# ---------------------------------------------------------------------------
# Informacao de Jogadores Online
# ---------------------------------------------------------------------------
# Ativa o comando de voz .online para o jogador verificar
# quantos jogadores estao conectados no servidor.
EnableOnlineCommand = False
