# ---------------------------------------------------------------------------
# Recompensa por PvP/PK
# ---------------------------------------------------------------------------
# Dar item de recompensa ao jogador que fizer PvP.
RewardPvpItem = False

# ID do item de recompensa por PvP.
RewardPvpItemId = 57

# Quantidade do item de recompensa por PvP.
RewardPvpItemAmount = 1000

# Exibir mensagem ao jogador quando receber a recompensa de PvP?
RewardPvpItemMessage = True

# Dar item de recompensa ao jogador que fizer PK (matar inocente).
RewardPkItem = False

# ID do item de recompensa por PK.
RewardPkItemId = 57

# Quantidade do item de recompensa por PK.
RewardPkItemAmount = 500

# Exibir mensagem ao jogador quando receber a recompensa de PK?
RewardPkItemMessage = True

# Desativar recompensas dentro de instancias (dungeons privadas).
DisableRewardsInInstances = True

# Desativar recompensas em zonas de PvP.
DisableRewardsInPvpZones = True
