# ---------------------------------------------------------------------------
# Mensagem de Boas-Vindas na Tela
# ---------------------------------------------------------------------------
# Exibe uma mensagem de boas-vindas na tela ao fazer login.
# Padrao: False
ScreenWelcomeMessageEnable = False

# Texto da mensagem de boas-vindas.
# Use '#' para quebra de linha (maximo 2 linhas).
ScreenWelcomeMessageText = Welcome to our server!

# Tempo (em segundos) que a mensagem ficara visivel na tela apos o login.
ScreenWelcomeMessageTime = 10
