# ---------------------------------------------------------------------------
# Exibir Horario do Servidor
# ---------------------------------------------------------------------------
# Ativa a exibicao do horario local do servidor atraves do comando /time.
DisplayServerTime = True
