# ---------------------------------------------------------------------------
# Titulo Inicial
# ---------------------------------------------------------------------------
# Ativa um titulo customizado para novos personagens.
# Se True, todo personagem recem-criado recebera o titulo definido abaixo.
# Padrao: False
EnableStartingTitle = False

# Texto do titulo que novos jogadores receberao.
StartingTitle = Newbie
