# ---------------------------------------------------------------------------
# Localizacao Inicial Customizada
# ---------------------------------------------------------------------------
# Ativa um ponto de spawn (nascimento) customizado para novos personagens.
# Se True, todos os novos personagens nascem nas coordenadas abaixo em vez do local padrao da raca.
# Padrao: False
CustomStartingLocation = False

# Coordenadas X, Y, Z do ponto de nascimento customizado.
# Padrao: 83020, 147880, -3469 (Giran)
CustomStartingLocX = 83020
CustomStartingLocY = 147880
CustomStartingLocZ = -3469
