# ---------------------------------------------------------------------------
# Ordenacao do Armazem
# Exibe a janela de retirada organizada por tipo de item (Armadura/Arma/Spellbook...).
# ---------------------------------------------------------------------------
# Ativar ordenacao no armazem do cla.
EnableWarehouseSortingClan = False
# Ativar ordenacao no armazem pessoal.
EnableWarehouseSortingPrivate = False
