DROP TABLE IF EXISTS `accounts`;
CREATE TABLE IF NOT EXISTS `accounts` (
  `login` VARCHAR(45) NOT NULL default '',
  `password` VARCHAR(45),
  `secondaryPassword` VARCHAR(32) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `accessLevel` TINYINT NOT NULL DEFAULT 0,
  `account_to_merge` varchar(32) DEFAULT '',
  `allow_ip` varchar(255) DEFAULT NULL,
  `allow_hwid` varchar(255) DEFAULT NULL,
  `ban_expire` int(11) NOT NULL DEFAULT '0',
  `bonus` double NOT NULL DEFAULT '1',
  `bonus_expire` int(11) NOT NULL DEFAULT '0',
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastactive` bigint(13) unsigned NOT NULL DEFAULT '0',
  `lastIP` CHAR(15) NULL DEFAULT NULL,
  `lastServer` TINYINT DEFAULT 1,
  `last_access` int(11) NOT NULL DEFAULT '0',
  `bot_report_points` int(10) NOT NULL DEFAULT '7',
  `points` int(11) NOT NULL default '0',
  `pcIp` char(15) DEFAULT NULL,
  `hop1` char(15) DEFAULT NULL,
  `hop2` char(15) DEFAULT NULL,
  `hop3` char(15) DEFAULT NULL,
  `hop4` char(15) DEFAULT NULL,
  PRIMARY KEY (`login`)
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;