# ---------------------------------------------------------------------------
# Налаштування інтерфейсу
# ---------------------------------------------------------------------------

# Увімкнути GUI -Syntax-Dev, коли ОС це підтримує.
# Надає доступ до команд адміністратора без потреби бути онлайн.
# За замовчуванням: True
EnableGUI = True

# Темна тема.
# Використовуйте темну версію теми Nimbus.
# За замовчуванням: True
DarkTheme = True
