# ---------------------------------------------------------------------------
# База даних
# ---------------------------------------------------------------------------

# Вкажіть клас драйвера JDBC для вашої бази даних.
# За замовчуванням : com.mysql.cj.jdbc.Driver
Driver = com.mysql.cj.jdbc.Driver

# URL бази даних
# За замовчуванням : jdbc:mysql://localhost/login?useUnicode=true&characterEncoding=utf-8&useSSL=false&connectTimeout=10000&interactiveClient=true&sessionVariables=wait_timeout=600,interactive_timeout=600&autoReconnect=true
URL = jdbc:mysql://localhost/login?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&connectTimeout=10000&interactiveClient=true&sessionVariables=wait_timeout=600,interactive_timeout=600&autoReconnect=true

# Інформація про користувача бази даних. За замовчуванням «root», але це не рекомендується.
Login = root

# Пароль користувача бази даних, залиште порожнім для відсутності пароля.
Password = qsmiim13fv

# Максимальна кількість з'єднань з базою даних, що підтримуються в пулі.
# За замовчуванням: 5
MaximumDatabaseConnections = 5

# Визначити, чи слід тестувати підключення до бази даних на доступність.
# За замовчуванням: False
TestDatabaseConnections = False


# ---------------------------------------------------------------------------
# Налаштування автоматичного резервного копіювання бази даних
# ---------------------------------------------------------------------------
# Створювати резервні копії бази даних під час перезапуску або вимкнення сервера.
BackupDatabase = True

# Шлях до папки з бінарними файлами MySQL. Потрібно лише на Windows.
MySqlBinLocation = C:/xampp/mysql/bin/

# Шлях, де зберігаються резервні копії MySQL.
BackupPath = ../backup/

# Максимальна кількість днів, протягом яких зберігатимуться резервні копії.
# Старі файли в папці резервних копій будуть видалені.
# Встановіть 0, щоб вимкнути.
BackupDays = 30
