# ---------------------------------------------------------------------------
# Налаштування сервера входу
# ---------------------------------------------------------------------------
# Це файл конфігурації сервера. Тут ви можете налаштувати інформацію про з'єднання для вашого сервера.
# Це написано з припущенням, що ви знаходитесь за роутером.
# Спрощені визначення...
# LAN (локальна мережа) - зазвичай складається з комп'ютерів, підключених до того ж роутера, що й ви.
# WAN (широка мережа) - зазвичай складається з комп'ютерів ПОZA вашим роутером (тобто інтернет).
# x.x.x.x - Формат IP-адреси. Не включайте x у налаштування. Мають бути реальні числа.

# ---------------------------------------------------------------------------
# Мережа
# ---------------------------------------------------------------------------

# IP для прив'язки LoginServer, використовуйте 0.0.0.0 для прив'язки до всіх доступних IP
# УВАГА: <u><b><font color="red">Будь ласка, не змінюйте IP за замовчуванням тут, якщо не знаєте, що робите!</font></b></u>
# УВАГА: <u><b><font color="red">Зовнішні/внутрішні IP тепер у файлі "ipconfig.xml".</font></b></u>
# За замовчуванням: 0.0.0.0
LoginserverHostname = 0.0.0.0

# За замовчуванням: 2106
LoginserverPort = 2106

# Адреса, на якій login буде слухати GameServers, використовуйте * для прив'язки до всіх доступних IP
# УВАГА: <u><b><font color="red">Будь ласка, не змінюйте стандартні IP тут, якщо не знаєте, що робите!</font></b></u>
# УВАГА: <u><b><font color="red">Зовнішні/Внутрішні IP тепер у файлі "ipconfig.xml".</font></b></u>
# За замовчуванням: 127.0.0.1
LoginHostname = 127.0.0.1

# Порт, на якому login буде слухати запити від GameServers
# За замовчуванням: 9014
LoginPort = 9014


# ---------------------------------------------------------------------------
# Конфігурація потоків
# ---------------------------------------------------------------------------

# Визначає кількість потоків у запланованому пулі потоків.
# Якщо встановлено -1, це буде визначено як кількість доступних процесорів, поділена на 2.
ScheduledThreadPoolSize = 2

# Визначає кількість потоків у миттєвому пулі потоків.
# Якщо встановлено -1, це буде визначено кількістю доступних процесорів, поділеною на 2.
InstantThreadPoolSize = 2


# ---------------------------------------------------------------------------
# Безпека
# ---------------------------------------------------------------------------

# Скільки разів ви можете ввести некоректні дані облікового запису/пароля, перш ніж IP буде заблоковано.
# За замовчуванням: 5
LoginTryBeforeBan = 5

# Час, протягом якого ви не зможете знову увійти в систему після LoginTryBeforeBan невдалих спроб входу.
# За замовчуванням: 900 (15 хвилин)
LoginBlockAfterBan = 900

# Якщо встановлено True, будь-який GameServer може зареєструватися на вільних слотах вашого логіну
# За замовчуванням: True
AcceptNewGameServer = True

# Захист від повені. Усі значення в мілісекундах.
# За замовчуванням: True
EnableFloodProtection = True

# За замовчуванням: 15
FastConnectionLimit = 15

# За замовчуванням: 700
NormalConnectionTime = 700

# За замовчуванням: 350
FastConnectionTime = 350

# За замовчуванням: 50
MaxConnectionPerIP = 50


# ---------------------------------------------------------------------------
# Різні налаштування входу
# ---------------------------------------------------------------------------

# Якщо False, ліцензію (після входу) не буде показано.
# За замовчуванням: True
ShowLicence = True

# За замовчуванням: True
AutoCreateAccounts = True

# Коренева директорія датапака.
# За замовчуванням — поточна директорія, з якої запущено сервер.
DatapackRoot = .


# ---------------------------------------------------------------------------
# Планове перезапущення входу
# ---------------------------------------------------------------------------

# Увімкнути/вимкнути планове перезапущення входу.
# За замовчуванням: False
LoginRestartSchedule = True
# Час у годинах.
# За замовчуванням: 24
LoginRestartTime = 24
