# ---------------------------------------------------------------------------
# Captcha - Protecao contra Bots
# ---------------------------------------------------------------------------
# Ativa o sistema de prevencao de bots.
EnableCaptcha = False

# Quantos monstros precisam ser mortos para ativar a validacao?
KillCounter = 100

# Faixa de valores aleatorios somados ao contador principal.
KillCounterRandomization = 50

# Resetar o contador de mortes por inatividade.
KillCounterReset = False

# Tempo para resetar o contador apos o ultimo mob morto (em minutos).
KillCounterResetTime = 20

# Tempo que a janela de validacao aguarda uma resposta (em segundos).
ValidationTime = 60

# Numero de tentativas se o jogador digitar o codigo errado.
# 1 = desativado.
CaptchaAttempts = 2

# Punicoes:
#	0 = mover o personagem para a vila mais proxima.
#	1 = desconectar o personagem do servidor.
#	2 = prender o personagem na cadeia.
#	3 = banir o personagem do servidor.
Punishment = 0

# Quanto tempo o personagem fica preso na cadeia? (em minutos)
# 0 = preso para sempre.
JailTime = 2

# Dobrar o tempo a cada entrada na cadeia.
# Apos 24h o tempo retorna ao valor inicial.
DoubleJailTime = False
