# ---------------------------------------------------------------------------
# Distancia Minima para Lojas Privadas
# ---------------------------------------------------------------------------
# Distancia minima de um jogador/NPC para abrir uma nova loja privada.
# Padrao: 0
ShopMinRangeFromPlayer = 50
ShopMinRangeFromNpc = 100
