# ---------------------------------------------------------------------------
# Protecao contra Walker/Bot
# ---------------------------------------------------------------------------
# Protecao basica contra L2Walker.
# Padrao: False
L2WalkerProtection = True
