# ---------------------------------------------------------------------------
# Anuncios de Bosses
# ---------------------------------------------------------------------------
# Ativa anuncios quando um RaidBoss nasce (spawn).
RaidBossSpawnAnnouncements = False

# Ativa anuncios quando um RaidBoss e derrotado.
RaidBossDefeatAnnouncements = False

# Ativa anuncios de RaidBoss dentro de instancias.
RaidBossInstanceAnnouncements = False

# Ativa anuncios quando um GrandBoss nasce (spawn).
GrandBossSpawnAnnouncements = False

# Ativa anuncios quando um GrandBoss e derrotado.
GrandBossDefeatAnnouncements = False

# Ativa anuncios de GrandBoss dentro de instancias.
GrandBossInstanceAnnouncements = False

# Exclui determinados Raid Bosses ou Grand Bosses dos anuncios de spawn.
# Adicione os IDs dos NPCs dos bosses a excluir, separados por virgula.
# Deixe vazio para incluir todos.
RaidbossExcludedFromSpawnAnnouncements = 

# Exclui determinados Raid Bosses ou Grand Bosses dos anuncios de derrota.
# Adicione os IDs dos NPCs dos bosses a excluir, separados por virgula.
# Deixe vazio para incluir todos.
RaidbossExcludedFromDefeatAnnouncements = 
