# ---------------------------------------------------------------------------
# Monstros Campeoes - Transforma mobs aleatorios em Campeoes
# ---------------------------------------------------------------------------
# Ativa/Desativa o sistema de Mobs Campeoes.
ChampionEnable = False

# Forca mobs Campeoes a serem passivos?
# False = mobs Campeoes mantem comportamento padrao/Agressivo.
# True = todos os mobs Campeoes ficam passivos.
ChampionPassive = False

# % de chance de um mob se tornar Campeao (0 para desativar).
ChampionFrequency = 5

# Titulo de todos os Mobs Campeoes.
ChampionTitle = Champion

# Aura vermelha para Mobs Campeoes.
ChampionAura = True

# Nivel minimo e maximo permitido para um mob ser Campeao.
ChampionMinLevel = 20
ChampionMaxLevel = 70

# Multiplicador de HP para Mobs Campeoes.
ChampionHp = 8

# Multiplicador de Regeneracao de HP para Mobs Campeoes.
ChampionHpRegen = 1.0

# Multiplicador de recompensa de Exp/Sp para Mobs Campeoes.
ChampionRewardsExpSp = 8.0

# Multiplicador de chance de recompensas normais para Mobs Campeoes.
ChampionRewardsChance = 8.0

# Multiplicador de quantidade de recompensas normais para Mobs Campeoes.
ChampionRewardsAmount = 1.0

# Multiplicador de chance de recompensa de Adena e Seal Stone para Mobs Campeoes.
ChampionAdenasRewardsChance = 1.0

# Multiplicador de quantidade de recompensa de Adena e Seal Stone para Mobs Campeoes.
ChampionAdenasRewardsAmount = 1.0

# Bonus de Ataque Fisico e Magico para Mobs Campeoes.
ChampionAtk = 1.0

# Bonus de Velocidade de Ataque Fisico/Magico para Mobs Campeoes.
ChampionSpdAtk = 1.0

# ID e quantidade de recompensa especial que o jogador recebe.
# Separado por ;
# Exemplo: 6393,1;57,5000
ChampionRewardItems = 6393,1

# % de chance de obter recompensa especial de um Mob Campeao de nivel inferior.
# Padrao: 0
ChampionRewardLowerLvlItemChance = 0

# % de chance de obter recompensa especial de um Mob Campeao de nivel superior.
# Padrao: 0
ChampionRewardHigherLvlItemChance = 100

# Ativa calculo de vitalidade ao matar mobs Campeoes?
# Cuidado: pode causar grande desbalanceamento no servidor, pois a taxa seria
# "mobXP x taxaServidor x taxaVitalidade x taxaCampeaoXp"
# Observacoes:
#	Funciona apenas se EnableVitality = True
# Padrao: False
ChampionEnableVitality = False

# Ativa nascimento de Campeoes dentro de instancias.
# Padrao: False
ChampionEnableInInstances = False
