# ---------------------------------------------------------------------------
# Gerenciador de Delevel (NPC para reduzir nivel)
# ---------------------------------------------------------------------------
# Ativa o NPC de Delevel.
# Padrao: False
Enabled = False

# ID do NPC de Delevel.
# Padrao: 36604
NpcId = 36604

# ID do item necessario para fazer delevel.
# Padrao: 4356 (Gold Einhasad)
RequiredItemId = 4356

# Quantidade do item necessario.
# Padrao: 2
RequiredItemCount = 2

# Nivel minimo que o jogador pode alcancar.
# Padrao: 20
MinimumDelevel = 20
