# ---------------------------------------------------------------------------
# Venda a Mercadores sem Lucro
# ---------------------------------------------------------------------------
# Todos os itens vendidos a mercadores nao dao nenhuma Adena.
MerchantZeroSellPrice = False
