# ---------------------------------------------------------------------------
# Mestre Nobless (NPC para virar nobless instantaneamente)
# ---------------------------------------------------------------------------
# Ativa o NPC Mestre Nobless.
# Padrao: False
Enabled = False

# ID do NPC Mestre Nobless.
# Padrao: 36605
NpcId = 36605

# Nivel necessario para se tornar nobless.
# Considere alterar os htmls se modificar este valor.
# Padrao: 80
LevelRequirement = 80

# Recompensar com tiara de nobless.
# Padrao: True
RewardTiara = True

# Moeda usada para pagamento.
# Padrao: 57 (Adena)
NoblessCoin = 57
NoblessCoinCount = 1000000000
