#=============================================================
#                          Buffer
#=============================================================
# Verifique tambem data\SchemeBufferSkills.xml
# Numero maximo de esquemas de buffs disponiveis por jogador.
BufferMaxSchemesPerChar = 4

# Item de pagamento para o buffer. Pode ser alterado para moeda customizada.
BufferItemId = 57

# Custo fixo de buffs. Sobrescreve o preco individual se diferente de -1.
BufferStaticCostPerBuff = -1
