# --------------------------------------------------
# Configuracao geral de Halls Conquistaveis
# --------------------------------------------------
# Nivel minimo do cla necessario para se registrar
# no cerco
MinClanLevel = 4

# Numero maximo de clas permitidos para a batalha
MaxAttackers = 50

# Numero maximo de bandeiras que cada cla pode
# colocar
MaxFlagsPerClan = 1

# Ativa a recompensa de fama
EnableFame = False

# Quantidade de fama
FameAmount = 0

# Frequencia da fama
FameFrequency = 0
