# ---------------------------------------------------------------------------
# Configuracoes de Guerra Territorial
# ---------------------------------------------------------------------------
# Duracao da guerra antes da contagem regressiva (em minutos).
# Padrao: 120
WarLength = 120

# Nivel minimo do cla para se registrar.
# Padrao: 0
ClanMinLevel = 0

# Nivel minimo do jogador para se registrar.
# Padrao: 40
PlayerMinLevel = 40

# Numero maximo de clas e jogadores que podem se registrar por lado.
# Padrao: 500
DefenderMaxClans = 500

# Padrao: 500
DefenderMaxPlayers = 500

# Jogadores segurando Ward podem ser atacados e mortos em zona de paz.
# Padrao: False
PlayerWithWardCanBeKilledInPeaceZone = False

# Spawnar Wards nos Castelos quando a Guerra Territorial nao esta em andamento.
# Padrao: False
SpawnWardsWhenTWIsNotInProgress = False

# Retornar todas as Wards para seus castelos quando a Guerra Territorial comecar.
# Padrao: False
# True: Corrige wards territoriais nao spawnando quando a Guerra Territorial inicia.
ReturnWardsWhenTWStarts = True

# Insignias Territoriais necessarias para se tornar Nobless.
# Padrao: 100
MinTerritoryBadgeForNobless = 100

# Insignias Territoriais necessarias para comprar Strider.
# Padrao: 50
MinTerritoryBadgeForStriders = 50

# Insignias Territoriais necessarias para comprar Guardian's Strider.
# Padrao: 80
MinTerritoryBadgeForBigStrider = 80
